# Generated by Django 2.1.1 on 2018-09-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('societe', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('number_1', models.IntegerField(blank=True, null=True)),
                ('number_2', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=300)),
                ('adresse', models.TextField(blank=True, unique=True)),
                ('quartier', models.CharField(max_length=120)),
                ('commune', models.CharField(max_length=120)),
                ('ville', models.CharField(max_length=120)),
                ('secteur_1', models.CharField(max_length=120)),
                ('secteur_2', models.CharField(max_length=120)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
