# Generated by Django 2.1.1 on 2018-09-21 13:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_post_site_web'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='province',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
    ]
