# Generated by Django 2.1.1 on 2018-09-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_post_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='commune',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='post',
            name='email',
            field=models.EmailField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='province',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='post',
            name='quartier',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='post',
            name='secteur_1',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='post',
            name='secteur_2',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='post',
            name='site_web',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
