# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-15 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0006_auto_20181015_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='number_1',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='number_2',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
