# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-16 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0010_auto_20181016_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='number_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='number_2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
