# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-17 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0011_auto_20181016_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='number_1',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='number_2',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
    ]
