# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-17 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0014_auto_20181017_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='number_1',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='number_2',
            field=models.IntegerField(blank=True, max_length=50),
        ),
    ]
